
################################################################
# Metadata
################################################################

# Basics
title:              emptydesk.space
email:              christopher.mills@alumni.ubc.ca
author:
  name:             'Chris Eugene Mills'
tagline:
description:
url:                http://emptydesk.space/
baseurl:            ''
# baseurl: /emptydesk.space

# Links
github:
  repo:             https://github.com/chrsmlls333
  project:          https://github.com/chrsmlls333/emptydesk.space
  username:         chrsmlls333

################################################################
# Configuration
################################################################

# Setup
destination:        ./_site

markdown:           redcarpet
highlighter:        rouge
sass:
  sass_dir:         _sass
  style:            compressed
exclude:            [Gemfile, Gemfile.lock] #, README.md]
include:            [.gitignore, .nojekyll]

# Page Structure

indexurl:           '/'
permalink:          /book/jpg/:title/
relative_permalinks: true
titlelink:          '/'

collections:
  filepages:
    output: true
    permalink: /book/:path/

# Google Analytics
analytics:
  active:           'true'
  userID:           'UA-64212356-5'
